### ISSUE TITLE
Support references in document

### ISSUE THREAD

**Issue by JordiPolo** [softprops/openapi#4]
Support intra document references
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#reference-object

I think most people uses this, even the petstore example uses this.

**Comment by softprops** [comment]
$ref is supported albeit maybe not in the most elegant way. It's used in thinks like schema and responses. Ill see if im missing areas

**Comment by JordiPolo** [comment]
I have a failure with the following document (a strip down version of a real doc). The doc shows no problems in the swagger editor so I assume it is correct:
```yaml
swagger: "2.0"
info:
  description: "My service rocks."
  version: "1.0.0"
  title: SOA Resource
  termsOfService: https://github.com/mdsol/resource_rocks
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  /v1/resource:
    get:
      description: "A filtered collection of resource "
      operationId: getResource
      parameters:
        - $ref: "#/parameters/per_page"

      responses:
        "404":
          description: Resource  not found

parameters:
  per_page:
    in: query
    name: per_page
    description: The number of results per page
    required: false
    type: integer
    default: 25
```

**Comment by softprops** [comment]
seems [legit](http://stackoverflow.com/questions/27005105/swagger-openapi-use-ref-to-pass-a-reusable-defined-parameter). I'll see if I can come up with a trick to support both.

**Comment by softprops** [comment]
I'm learning how awesome [enum serialization](https://serde.rs/enum-representations.html) is in serde. Unfortunately I ran to a little [gotcha](https://github.com/serde-rs/serde/issues/910) with a enum approach for this

**Comment by softprops** [comment]
I'll look into a other alternatives

**Comment by JordiPolo** [comment]
Cool, thanks! I've tested with a longer document and it works well!

**Comment by softprops** [comment]
@JordiPolo  what are your usecases for this crate atm? I realized yesterday that I could get alot more of of serde's enum support that I expected so I started a branch to do that but I realized that's going to probably be a breaking change. I kind of expected that this early in the process but now that I know someone is use this I'm a little bit hesitant to move too fast.

**Comment by JordiPolo** [comment]
Thanks for reaching out!
No worries, break it as much as you want.
In my company we may need to write a converter from openapi to another spec format and maybe I can get away with using Rust. 
At this moment I'm just checking what libraries are out there so if we do this I can have a sense of how difficult it is.

**Comment by softprops** [comment]
It's funny you mention that! That's exactly what I was going for with this. I started a similar thing where i work https://github.com/meetup/openbars. Think swagger codegen sans the java dependency and using handlebars. Its very rough and spent come bundled with templates but I plan to build a community around it. I have a  closed source and incomplete rust template but there's nothing stopping others from making open and sharable templates.

**Comment by JordiPolo** [comment]
If you were to use mustache, you may be able to use all the templates from the swagger-codegen project. If you check the activity there, it is quite crazy the amount of collaboration and it would be difficult to build a community at any level near that.
There is another project called Autorest done in C# and worked on by paid developers by Microsoft but they can not maintain that level

**Comment by JordiPolo** [comment]
I've started a tool based on your library. https://github.com/JordiPolo/oatool
Do not hesitate doing breaking changes, the code I've written is terrible and want to rewrite it all
